ARG NODE_VERSION=24-bookworm-slim


FROM node:${NODE_VERSION} AS node-dev

WORKDIR /app

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        bash \
        git \
        ca-certificates \
        curl \
    ;

EXPOSE 4200

#ENTRYPOINT ["docker-entrypoint-dev"]
#CMD ["bash"]
