api_platform:
    title: Club API
    version: 1.0.0
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
    docs_formats:
        json: [ 'application/json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
