security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        connection_user_provider:
            entity:
                class: App\Entity\ConnectionUser
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false


        login:
            pattern: ^/api/v1/auth/login$
            stateless: true
            provider: connection_user_provider
            user_checker: App\Security\ConnectionUserChecker
            login_throttling:
                max_attempts: 5
                interval: '1 minute'
            json_login:
                check_path: api_auth_login
                username_path: email
                password_path: password
                success_handler: App\Security\Authentication\LoginSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure


        api:
            pattern: ^/api
            stateless: true
            provider: connection_user_provider
            user_checker: App\Security\ConnectionUserChecker
            jwt: ~

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/api/v1/auth/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/refresh$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/logout$, roles: PUBLIC_ACCESS }

        # Documentation API Platform
        - { path: ^/api/?$, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/contexts, roles: PUBLIC_ACCESS }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
